export const PrintService = {
  generateReceiptHTML(invoice, lineItems, company = {}, isGst = false) {
    const itemsHtml = lineItems.map((item, i) => `
      <tr>
        <td style="padding:4px 2px;font-size:10px;border-bottom:1px dashed #ccc;">${i + 1}</td>
        <td style="padding:4px 2px;font-size:10px;border-bottom:1px dashed #ccc;">${item.name || 'Item'}</td>
        <td style="padding:4px 2px;font-size:10px;border-bottom:1px dashed #ccc;text-align:center;">${item.purity || ''}</td>
        <td style="padding:4px 2px;font-size:10px;border-bottom:1px dashed #ccc;text-align:right;">${(item.weight || 0).toFixed(3)}</td>
        <td style="padding:4px 2px;font-size:10px;border-bottom:1px dashed #ccc;text-align:right;">${(item.qty || 1).toFixed(2)}</td>
        <td style="padding:4px 2px;font-size:10px;border-bottom:1px dashed #ccc;text-align:right;">${formatNum(item.rate)}</td>
        <td style="padding:4px 2px;font-size:10px;border-bottom:1px dashed #ccc;text-align:right;">${formatNum(item.amount)}</td>
      </tr>
    `).join('');

    const gstAmt = invoice.gst_amount || 0;
    const gstSection = isGst ? `
      <tr><td colspan="2" style="padding:2px;font-size:9px;">CGST: ${formatNum(gstAmt / 2)}</td>
      <td style="padding:2px;font-size:9px;text-align:right;">SGST: ${formatNum(gstAmt / 2)}</td></tr>
      <tr><td colspan="3" style="padding:2px;font-size:9px;font-weight:bold;">Total GST: ${formatNum(gstAmt)}</td></tr>
    ` : '';

    return `<!DOCTYPE html><html><head>
<style>
  @page { margin: 8mm; size: ${invoice.paperWidth || '80'}mm ${invoice.paperHeight || '297'}mm; }
  body { font-family: 'Courier New', monospace; font-size: 10px; margin: 0; padding: 8px; color: #000; }
  table { width: 100%; border-collapse: collapse; }
  .header { text-align: center; margin-bottom: 8px; }
  .header h2 { margin: 0; font-size: 14px; }
  .header p { margin: 2px 0; font-size: 9px; }
  .divider { border-top: 1px dashed #000; margin: 6px 0; }
  .footer { text-align: center; font-size: 9px; margin-top: 8px; }
</style></head><body>
<div class="header">
  <h2>${company.companyName || 'Arynoxtech Jwellery'}</h2>
  <p>${company.address || ''}</p>
  <p>${company.phone ? 'Ph: ' + company.phone : ''} ${company.gstin ? 'GST: ' + company.gstin : ''}</p>
  <div class="divider"></div>
  <h3 style="margin:4px 0;">${isGst ? 'TAX INVOICE' : 'CASH MEMO'}</h3>
</div>
<table style="font-size:9px;">
  <tr><td>Invoice: <b>${invoice.voucher_no}</b></td><td style="text-align:right;">Date: ${invoice.date}</td></tr>
  <tr><td>Customer: <b>${invoice.party_name || 'Walk-in'}</b></td>
  ${isGst ? '<td style="text-align:right;">GST: ' + (invoice.gstin || '') + '</td>' : '<td></td>'}</tr>
</table>
<div class="divider"></div>
<table>
  <thead><tr style="font-size:9px;font-weight:bold;">
    <th style="text-align:left;">#</th><th style="text-align:left;">Item</th><th>Purity</th>
    <th style="text-align:right;">Wt</th><th style="text-align:right;">Qty</th>
    <th style="text-align:right;">Rate</th><th style="text-align:right;">Amt</th>
  </tr></thead>
  <tbody>${itemsHtml}</tbody>
</table>
<div class="divider"></div>
<table style="font-size:10px;">
  <tr><td><b>Total Weight:</b> ${(invoice.gold_weight || 0).toFixed(3)} g</td>
  <td style="text-align:right;"><b>Total Amount: ₹${formatNum(invoice.total_amount)}</b></td></tr>
  ${gstSection}
</table>
<div class="divider"></div>
<table style="font-size:9px;">
  <tr><td>Payment: ${invoice.payment_mode || 'Cash'}</td><td style="text-align:right;">Amount: ₹${formatNum(invoice.total_amount)}</td></tr>
</table>
<div class="footer">
  <p>*** Thank you for your business! ***</p>
  <p style="font-size:8px;">Digitally generated by Arynoxtech Jwellery ERP</p>
</div>
</body></html>`;
  },

  generateBarcodeHTML(items, settings) {
    const stickerWidth = settings.stickerWidth || 66;
    const stickerHeight = settings.stickerHeight || 10;
    const cols = settings.columns || 1;
    const isSmall = stickerHeight <= 15;

    const itemsHtml = items.map(item => {
      if (isSmall) {
        return `
      <div class="sticker" style="width:${stickerWidth}mm;height:${stickerHeight}mm;flex-direction:row;gap:2px;padding:0 1mm;">
        <div style="flex:1;overflow:hidden;">
          <div class="barcode-wrap" style="height:${Math.max(6, stickerHeight - 2)}mm;">
            <img src="${item.barcodeImg || 'https://barcode.tec-it.com/barcode.ashx?data=' + (item.barcode || item.code || 'N/A') + '&code=Code128&dpi=96'}" style="height:100%;width:auto;" />
          </div>
        </div>
        <div style="text-align:right;white-space:nowrap;">
          <div class="item-name" style="font-size:${Math.max(5, settings.nameSize || 5)}px;">₹${formatNum(item.selling_price || 0)}</div>
          <div class="barcode-text">${item.barcode || item.code || ''}</div>
        </div>
      </div>`;
      }
      return `
      <div class="sticker" style="width:${stickerWidth}mm;height:${stickerHeight}mm;">
        <div class="item-name">${item.name}</div>
        <div class="item-details">
          <span>Wt: ${(item.weight || 0).toFixed(3)}g</span>
          <span>₹${formatNum(item.selling_price || 0)}</span>
        </div>
        <div class="barcode-wrap">
          <img src="${item.barcodeImg || 'https://barcode.tec-it.com/barcode.ashx?data=' + (item.barcode || item.code || 'N/A') + '&code=Code128&dpi=96'}" style="width:100%;height:${Math.max(8, stickerHeight * 0.3)}mm;" />
        </div>
        <div class="barcode-text">${item.barcode || item.code || ''}</div>
        ${settings.showQty ? '<div class="qty">Qty: ' + (item.qty || 1) + '</div>' : ''}
      </div>`;
    }).join('');

    const gapVal = settings.gap || 1;
    const marginVal = settings.margin || 1;

    return `<!DOCTYPE html><html><head>
<style>
  @page { margin: 0; size: ${settings.pageWidth || 66}mm ${settings.pageHeight || 10}mm; }
  body { margin: 0; padding: ${marginVal}mm; font-family: Arial, sans-serif; }
  .sticker-grid { display: grid; grid-template-columns: repeat(${cols}, 1fr); gap: ${gapVal}mm; }
  .sticker { border: ${settings.border ? '1px dashed #999' : 'none'}; 
    display: flex; flex-direction: column; align-items: center; justify-content: center;
    text-align: center; padding: 0; box-sizing: border-box; overflow: hidden; }
  .item-name { font-size: ${settings.nameSize || 5}px; font-weight: bold; line-height: 1.2; }
  .item-details { font-size: ${settings.detailSize || 5}px; display: flex; gap: 4px; line-height: 1.2; }
  .barcode-wrap { width: 100%; margin: 0; display: flex; align-items: center; justify-content: center; }
  .barcode-text { font-size: 4px; color: #333; line-height: 1; }
  .qty { font-size: 5px; font-weight: bold; }
</style></head><body>
<div class="sticker-grid">${itemsHtml}</div>
</body></html>`;
  },

  generateBarcodeSingleHTML(item, settings) {
    const sw = settings.stickerWidth || 66;
    const sh = settings.stickerHeight || 10;
    const isSmall = sh <= 15;

    if (isSmall) {
      return `<!DOCTYPE html><html><head>
<style>
  @page { margin: 0; size: ${sw}mm ${sh}mm; }
  body { margin: 0; padding: 0; font-family: Arial, sans-serif; width: ${sw}mm; height: ${sh}mm;
    display: flex; flex-direction: row; align-items: center; overflow: hidden; }
  .barcode-wrap { flex: 1; height: 100%; display: flex; align-items: center; }
  .barcode-wrap img { height: 90%; max-width: 100%; }
  .info { text-align: right; padding-right: 1mm; white-space: nowrap; }
  .price { font-size: ${Math.max(5, settings.nameSize || 5)}px; font-weight: bold; }
  .code { font-size: 4px; color: #333; }
</style></head><body>
  <div class="barcode-wrap">
    <img src="${item.barcodeImg || 'https://barcode.tec-it.com/barcode.ashx?data=' + (item.barcode || item.code || 'N/A') + '&code=Code128&dpi=96'}" />
  </div>
  <div class="info">
    <div class="price">₹${formatNum(item.selling_price || 0)}</div>
    <div class="code">${item.barcode || item.code || ''}</div>
  </div>
</body></html>`;
    }

    return `<!DOCTYPE html><html><head>
<style>
  @page { margin: 0; size: ${sw}mm ${sh}mm; }
  body { margin: 0; padding: 2mm; font-family: Arial, sans-serif; width: ${sw}mm; height: ${sh}mm;
    display: flex; flex-direction: column; align-items: center; justify-content: center; text-align: center; }
  .item-name { font-size: ${settings.nameSize || 8}px; font-weight: bold; }
  .item-details { font-size: ${settings.detailSize || 7}px; }
  .barcode-wrap { width: 100%; margin: 1px 0; }
  .barcode-text { font-size: 6px; }
</style></head><body>
  <div class="item-name">${item.name}</div>
  <div class="item-details">${(item.weight || 0).toFixed(3)}g | ₹${formatNum(item.selling_price || 0)}</div>
  <div class="barcode-wrap">
    <img src="${item.barcodeImg || 'https://barcode.tec-it.com/barcode.ashx?data=' + (item.barcode || item.code || 'N/A') + '&code=Code128&dpi=96&imagetype=png'}" style="width:100%;height:${Math.max(8, sh * 0.35)}mm;" />
  </div>
  <div class="barcode-text">${item.barcode || item.code || ''}</div>
</body></html>`;
  }
};

export function generateA4ReceiptHTML(invoice, lineItems, company = {}, isGst = false) {
  const itemsHtml = lineItems.map((item, i) => `
    <tr>
      <td style="padding:6px 4px;font-size:11px;border-bottom:1px solid #ddd;text-align:center;">${i + 1}</td>
      <td style="padding:6px 4px;font-size:11px;border-bottom:1px solid #ddd;">${item.name || 'Item'}</td>
      <td style="padding:6px 4px;font-size:11px;border-bottom:1px solid #ddd;text-align:center;">${item.purity || ''}</td>
      <td style="padding:6px 4px;font-size:11px;border-bottom:1px solid #ddd;text-align:right;">${(item.weight || 0).toFixed(3)}</td>
      <td style="padding:6px 4px;font-size:11px;border-bottom:1px solid #ddd;text-align:right;">${(item.qty || 1).toFixed(2)}</td>
      <td style="padding:6px 4px;font-size:11px;border-bottom:1px solid #ddd;text-align:right;">${formatNum(item.rate || 0)}</td>
      <td style="padding:6px 4px;font-size:11px;border-bottom:1px solid #ddd;text-align:right;">${formatNum(item.making_charges || 0)}</td>
      <td style="padding:6px 4px;font-size:11px;border-bottom:1px solid #ddd;text-align:right;">${formatNum(item.discount || 0)}</td>
      <td style="padding:6px 4px;font-size:11px;border-bottom:1px solid #ddd;text-align:right;font-weight:bold;">${formatNum(item.amount)}</td>
    </tr>
  `).join('');

  const gstAmt = invoice.gst_amount || 0;
  const gstRows = isGst ? `
    <tr><td colspan="8" style="text-align:right;padding:4px;font-size:11px;font-weight:bold;">CGST:</td><td style="text-align:right;padding:4px;font-size:11px;">${formatNum(gstAmt / 2)}</td></tr>
    <tr><td colspan="8" style="text-align:right;padding:4px;font-size:11px;font-weight:bold;">SGST:</td><td style="text-align:right;padding:4px;font-size:11px;">${formatNum(gstAmt / 2)}</td></tr>
    <tr><td colspan="8" style="text-align:right;padding:4px;font-size:11px;font-weight:bold;">Total GST:</td><td style="text-align:right;padding:4px;font-size:11px;font-weight:bold;">${formatNum(gstAmt)}</td></tr>
  ` : '';

  const total = isGst ? (invoice.total_amount || 0) + (gstAmt) : (invoice.total_amount || 0);

  return `<!DOCTYPE html><html><head>
<style>
  @page { margin: ${invoice.marginTop || 10}mm ${invoice.marginRight || 10}mm ${invoice.marginBottom || 10}mm ${invoice.marginLeft || 10}mm; size: ${invoice.paperWidth || 210}mm ${invoice.paperHeight || 297}mm; }
  body { font-family: Arial, sans-serif; font-size: 12px; margin: 0; padding: 0; color: #000; }
  table { width: 100%; border-collapse: collapse; }
  .header { text-align: center; margin-bottom: 16px; padding-bottom: 12px; border-bottom: 2px solid #000; }
  .header h1 { margin: 0; font-size: 20px; text-transform: uppercase; }
  .header p { margin: 2px 0; font-size: 11px; color: #333; }
  .invoice-title { text-align: center; font-size: 16px; font-weight: bold; margin: 12px 0; text-transform: uppercase; letter-spacing: 1px; }
  .info-table td { padding: 2px 4px; font-size: 11px; }
  .divider { border-top: 1px solid #000; margin: 8px 0; }
  .footer { text-align: center; margin-top: 24px; padding-top: 12px; border-top: 1px solid #000; font-size: 10px; color: #555; }
  .terms { font-size: 10px; color: #555; margin-top: 12px; }
  .amount-words { font-size: 11px; font-weight: bold; margin-top: 8px; }
  th { background: #f0f0f0; padding: 8px 4px; font-size: 11px; text-align: center; border-bottom: 2px solid #000; }
</style></head><body>
<div class="header">
  <h1>${company.companyName || 'Arynoxtech Jwellery'}</h1>
  <p>${company.address || ''}</p>
  <p>${company.phone ? 'Ph: ' + company.phone : ''} ${company.email ? '| Email: ' + company.email : ''}</p>
  ${company.gstin ? '<p>GSTIN: ' + company.gstin + '</p>' : ''}
</div>
<div class="invoice-title">${isGst ? 'TAX INVOICE' : 'CASH MEMO'}</div>
<table class="info-table">
  <tr><td><b>Invoice No:</b> ${invoice.voucher_no}</td><td style="text-align:right;"><b>Date:</b> ${invoice.date}</td></tr>
  <tr><td><b>Customer:</b> ${invoice.party_name || 'Walk-in Customer'}</td>
  ${isGst ? '<td style="text-align:right;"><b>GSTIN:</b> ' + (invoice.gstin || '') + '</td>' : '<td></td>'}</tr>
  ${invoice.party_address ? '<tr><td colspan="2"><b>Address:</b> ' + invoice.party_address + '</td></tr>' : ''}
</table>
<div class="divider"></div>
<table>
  <thead><tr>
    <th style="width:30px;">#</th><th style="text-align:left;">Item</th><th style="width:50px;">Purity</th>
    <th style="width:60px;">Weight</th><th style="width:40px;">Qty</th><th style="width:65px;">Rate</th>
    <th style="width:65px;">Making</th><th style="width:55px;">Disc</th><th style="width:75px;">Amount</th>
  </tr></thead>
  <tbody>${itemsHtml}</tbody>
</table>
<div class="divider"></div>
<table>
  <tr><td colspan="8" style="font-size:11px;"><b>Total Weight:</b> ${(invoice.gold_weight || 0).toFixed(3)} g</td>
  <td style="text-align:right;font-size:14px;font-weight:bold;">₹${formatNum(total)}</td></tr>
  ${gstRows}
  <tr><td colspan="8"><b>Payment Mode:</b> ${invoice.payment_mode || 'Cash'}</td>
  <td style="text-align:right;font-size:12px;"><b>Net: ₹${formatNum(total)}</b></td></tr>
</table>
<div class="terms">
  <p><b>Terms & Conditions:</b></p>
  <p>1. All disputes subject to local jurisdiction. 2. Goods once sold will not be taken back. 3. This is a computer generated invoice.</p>
</div>
<div class="footer">
  <p>*** This is a computer generated invoice ***</p>
  <p style="font-size:9px;">Generated by Arynoxtech Jwellery ERP v2.0.0</p>
</div>
</body></html>`;
}

export const DEFAULT_BARCODE_SETTINGS = {
  stickerWidth: 66, stickerHeight: 10, columns: 1, gap: 1, margin: 1,
  nameSize: 5, detailSize: 5, border: false, showQty: false,
  pageWidth: 66, pageHeight: 10
};

export const BARCODE_PRESETS = {
  '66x10_Sticker': { label: '66x10mm Sticker', stickerWidth: 66, stickerHeight: 10, columns: 1, gap: 1, margin: 1, nameSize: 5, detailSize: 5, border: false, showQty: false, pageWidth: 66, pageHeight: 10 },
  '50x30_Label': { label: '50x30mm Label', stickerWidth: 50, stickerHeight: 30, columns: 2, gap: 2, margin: 5, nameSize: 8, detailSize: 7, border: true, showQty: true, pageWidth: 210, pageHeight: 297 },
  '100x50_Label': { label: '100x50mm Label', stickerWidth: 100, stickerHeight: 50, columns: 1, gap: 2, margin: 5, nameSize: 10, detailSize: 8, border: true, showQty: true, pageWidth: 210, pageHeight: 297 },
  'A4_Multi': { label: 'A4 Multi Label', stickerWidth: 66, stickerHeight: 10, columns: 3, gap: 1, margin: 5, nameSize: 5, detailSize: 5, border: false, showQty: false, pageWidth: 210, pageHeight: 297 },
};

function formatNum(n) {
  return new Intl.NumberFormat('en-IN', { maximumFractionDigits: 2, minimumFractionDigits: 2 }).format(n || 0);
}
